name: main

on:
  push:
    branches:
      - main
      - Dev_Josh
  pull_request:
    branches:
    - main
    - Dev_Josh

jobs:
  build-and-test:
    runs-on: ubuntu-latest
    steps:
      - name: Dummy step to pass CI
        run: echo "Skipping actual build and test for now"
